### ISSUE TITLE
Ability to specify iterator type on initialization

### ISSUE THREAD

**Issue by robertaves** [theburningmonk/ReactoKinesix#61]
I have code i'd like to port over to this library. I currently have 2 shards and a iterator id like to start at via a seq number. is there any way to do this? Is the default TRIM HORIZON or LATEST?

**Comment by theburningmonk** [comment]
The default is to use TRIM HORIZON.

One way to do what you want would be to manually create the Dynamo DB table and set the iterator values for the shards. That way, when the shard processors start they'll start with the given iterator. You can test it out against a different Kinesis stream first to see what the table looks like (there's only one table per kinesis app) and use that to guide you.

Alternatively, and this might make for a smoother transition:
1) create a new Kinesis stream, and scale it to the same number of shards as your current stream
2) start your ReactoKinesis app against the new stream (against TRIM HORIZON)
3) update your existing Kinesis consumer to just copy the data to the new Kinesis stream
4) update your producer for the existing Kinesis to write directly to the new stream
5) turn off existing Kinesis consumer app

**Comment by theburningmonk** [comment]
@robertaves did my comment above answer your question?

**Comment by robertaves** [comment]
Yes, thanks! i'll drain my shard and rename, seems like the best solution.

**Comment by theburningmonk** [comment]
No probs. I'll close the issue for now, feel free to reopen if you need further help with this.

Good luck! :-)
